// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.9
// source: proto/system.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SystemMonitor_GetMetrics_FullMethodName = "/system.SystemMonitor/GetMetrics"
)

// SystemMonitorClient is the client API for SystemMonitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemMonitorClient interface {
	GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error)
}

type systemMonitorClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemMonitorClient(cc grpc.ClientConnInterface) SystemMonitorClient {
	return &systemMonitorClient{cc}
}

func (c *systemMonitorClient) GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, SystemMonitor_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemMonitorServer is the server API for SystemMonitor service.
// All implementations must embed UnimplementedSystemMonitorServer
// for forward compatibility.
type SystemMonitorServer interface {
	GetMetrics(context.Context, *MetricsRequest) (*MetricsResponse, error)
	mustEmbedUnimplementedSystemMonitorServer()
}

// UnimplementedSystemMonitorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemMonitorServer struct{}

func (UnimplementedSystemMonitorServer) GetMetrics(context.Context, *MetricsRequest) (*MetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedSystemMonitorServer) mustEmbedUnimplementedSystemMonitorServer() {}
func (UnimplementedSystemMonitorServer) testEmbeddedByValue()                       {}

// UnsafeSystemMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemMonitorServer will
// result in compilation errors.
type UnsafeSystemMonitorServer interface {
	mustEmbedUnimplementedSystemMonitorServer()
}

func RegisterSystemMonitorServer(s grpc.ServiceRegistrar, srv SystemMonitorServer) {
	// If the following call pancis, it indicates UnimplementedSystemMonitorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemMonitor_ServiceDesc, srv)
}

func _SystemMonitor_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).GetMetrics(ctx, req.(*MetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemMonitor_ServiceDesc is the grpc.ServiceDesc for SystemMonitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemMonitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "system.SystemMonitor",
	HandlerType: (*SystemMonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetrics",
			Handler:    _SystemMonitor_GetMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/system.proto",
}
