// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.9
// source: proto/system.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_system_proto_rawDescGZIP(), []int{0}
}

type VitalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float32                `protobuf:"fixed32,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsage      float32                `protobuf:"fixed32,2,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VitalsResponse) Reset() {
	*x = VitalsResponse{}
	mi := &file_proto_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VitalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VitalsResponse) ProtoMessage() {}

func (x *VitalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VitalsResponse.ProtoReflect.Descriptor instead.
func (*VitalsResponse) Descriptor() ([]byte, []int) {
	return file_proto_system_proto_rawDescGZIP(), []int{1}
}

func (x *VitalsResponse) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *VitalsResponse) GetRamUsage() float32 {
	if x != nil {
		return x.RamUsage
	}
	return 0
}

var File_proto_system_proto protoreflect.FileDescriptor

const file_proto_system_proto_rawDesc = "" +
	"\n" +
	"\x12proto/system.proto\x12\vperformance\"\a\n" +
	"\x05Empty\"J\n" +
	"\x0eVitalsResponse\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x02R\bcpuUsage\x12\x1b\n" +
	"\tram_usage\x18\x02 \x01(\x02R\bramUsage2R\n" +
	"\x12PerformanceService\x12<\n" +
	"\tGetVitals\x12\x12.performance.Empty\x1a\x1b.performance.VitalsResponseB#Z!grpc-performance-test/proto;protob\x06proto3"

var (
	file_proto_system_proto_rawDescOnce sync.Once
	file_proto_system_proto_rawDescData []byte
)

func file_proto_system_proto_rawDescGZIP() []byte {
	file_proto_system_proto_rawDescOnce.Do(func() {
		file_proto_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_system_proto_rawDesc), len(file_proto_system_proto_rawDesc)))
	})
	return file_proto_system_proto_rawDescData
}

var file_proto_system_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_system_proto_goTypes = []any{
	(*Empty)(nil),          // 0: performance.Empty
	(*VitalsResponse)(nil), // 1: performance.VitalsResponse
}
var file_proto_system_proto_depIdxs = []int32{
	0, // 0: performance.PerformanceService.GetVitals:input_type -> performance.Empty
	1, // 1: performance.PerformanceService.GetVitals:output_type -> performance.VitalsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_system_proto_init() }
func file_proto_system_proto_init() {
	if File_proto_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_system_proto_rawDesc), len(file_proto_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_system_proto_goTypes,
		DependencyIndexes: file_proto_system_proto_depIdxs,
		MessageInfos:      file_proto_system_proto_msgTypes,
	}.Build()
	File_proto_system_proto = out.File
	file_proto_system_proto_goTypes = nil
	file_proto_system_proto_depIdxs = nil
}
