// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.9
// source: proto/system.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_proto_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_system_proto_rawDescGZIP(), []int{0}
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`   // CPU usage %
	RamUsage      float64                `protobuf:"fixed64,2,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`   // RAM usage %
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                   // Capture time
	NetIn         uint64                 `protobuf:"varint,4,opt,name=net_in,json=netIn,proto3" json:"net_in,omitempty"`             // Bytes received
	NetOut        uint64                 `protobuf:"varint,5,opt,name=net_out,json=netOut,proto3" json:"net_out,omitempty"`          // Bytes sent
	DiskRead      uint64                 `protobuf:"varint,6,opt,name=disk_read,json=diskRead,proto3" json:"disk_read,omitempty"`    // Disk read bytes
	DiskWrite     uint64                 `protobuf:"varint,7,opt,name=disk_write,json=diskWrite,proto3" json:"disk_write,omitempty"` // Disk write bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_proto_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_system_proto_rawDescGZIP(), []int{1}
}

func (x *MetricsResponse) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *MetricsResponse) GetRamUsage() float64 {
	if x != nil {
		return x.RamUsage
	}
	return 0
}

func (x *MetricsResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *MetricsResponse) GetNetIn() uint64 {
	if x != nil {
		return x.NetIn
	}
	return 0
}

func (x *MetricsResponse) GetNetOut() uint64 {
	if x != nil {
		return x.NetOut
	}
	return 0
}

func (x *MetricsResponse) GetDiskRead() uint64 {
	if x != nil {
		return x.DiskRead
	}
	return 0
}

func (x *MetricsResponse) GetDiskWrite() uint64 {
	if x != nil {
		return x.DiskWrite
	}
	return 0
}

var File_proto_system_proto protoreflect.FileDescriptor

const file_proto_system_proto_rawDesc = "" +
	"\n" +
	"\x12proto/system.proto\x12\x06system\"\x10\n" +
	"\x0eMetricsRequest\"\xd5\x01\n" +
	"\x0fMetricsResponse\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12\x1b\n" +
	"\tram_usage\x18\x02 \x01(\x01R\bramUsage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12\x15\n" +
	"\x06net_in\x18\x04 \x01(\x04R\x05netIn\x12\x17\n" +
	"\anet_out\x18\x05 \x01(\x04R\x06netOut\x12\x1b\n" +
	"\tdisk_read\x18\x06 \x01(\x04R\bdiskRead\x12\x1d\n" +
	"\n" +
	"disk_write\x18\a \x01(\x04R\tdiskWrite2N\n" +
	"\rSystemMonitor\x12=\n" +
	"\n" +
	"GetMetrics\x12\x16.system.MetricsRequest\x1a\x17.system.MetricsResponseB Z\x1eexample.com/system/proto;protob\x06proto3"

var (
	file_proto_system_proto_rawDescOnce sync.Once
	file_proto_system_proto_rawDescData []byte
)

func file_proto_system_proto_rawDescGZIP() []byte {
	file_proto_system_proto_rawDescOnce.Do(func() {
		file_proto_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_system_proto_rawDesc), len(file_proto_system_proto_rawDesc)))
	})
	return file_proto_system_proto_rawDescData
}

var file_proto_system_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_system_proto_goTypes = []any{
	(*MetricsRequest)(nil),  // 0: system.MetricsRequest
	(*MetricsResponse)(nil), // 1: system.MetricsResponse
}
var file_proto_system_proto_depIdxs = []int32{
	0, // 0: system.SystemMonitor.GetMetrics:input_type -> system.MetricsRequest
	1, // 1: system.SystemMonitor.GetMetrics:output_type -> system.MetricsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_system_proto_init() }
func file_proto_system_proto_init() {
	if File_proto_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_system_proto_rawDesc), len(file_proto_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_system_proto_goTypes,
		DependencyIndexes: file_proto_system_proto_depIdxs,
		MessageInfos:      file_proto_system_proto_msgTypes,
	}.Build()
	File_proto_system_proto = out.File
	file_proto_system_proto_goTypes = nil
	file_proto_system_proto_depIdxs = nil
}
